# INFORMACIÓN DEL PROYECTO

### TÍTULO

In [ ]:
#Escribe el título del proyecto en Markdown
titulo = "WTA Match Predictor: un modelo de predicción de resultados en el circuito femenino de tenis"

### TEMA

In [ ]:
# Describe brevemente el tema del proyecto en Markdown
tema = "Modelo de machine learning entrenado sobre 44.000 partidos históricos del circuito WTA " \
"(2007-2026) para " "predecir el resultado de partidos individuales. A partir de datos públicos se construyen features temporales " \
"como forma reciente, win rate por superficie o head-to-head. Además de las métricas propias de clasificación" \
"por la naturaleza de la predicción se usará también como métrica las probabilidades de " \
"las casas de apuestas Aplicar el modelo entrenado a un caso real mediante la simulación del cuadro de Roland Garros 2026"

In [ ]:
# Idea adicional: Clusterizar jugadoras por perfiles y añadir ese perfilado como feature

### OBJETIVOS

Define aquí el objetivo del proyecto

- Construir un pipeline completo de ML aplicado a datos deportivos reales, desde la limpieza y exploración hasta la predicción, incluyendo feature engineering temporal.
- Desarrollar un modelo de clasificación capaz de predecir el resultado de un partido WTA a partir de información disponible antes de su disputa
- Evaluar el rendimiento del modelo usando las probabilidades implícitas de las casas de apuestas como benchmark externo, midiendo hasta qué punto un modelo basado en datos públicos puede aproximarse al mercado.
- Aplicar el modelo entrenado a un caso real mediante la simulación del cuadro de Roland Garros 2026 con el método de Monte Carlo, obteniendo probabilidades de victoria para cada jugadora.

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [ ]:
# El dataset principal es el histórico de partidos de la WTA desde 2007 actualizado diariamente: "WTA Tennis 
# 2007 - 2026 Daily update"
# https://www.kaggle.com/datasets/dissfya/wta-tennis-2007-2023-daily-update
# Fuente Kaggle
# Hay otro dataset con estadísticas más completas de los partidos pero que llega sólo a 2024. Me he decidido por el 
# primero porque quiero hacer la predicción de Roland Garros 2026.
# Jeff Sackman github: https://github.com/JeffSackmann/tennis_wta

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [2]:
# Primer dataset
import pandas as pd
wta = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta.csv", low_memory= False)
wta.head()

,Tournament,Date,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,1.33,3,6-1 6-1
1,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,1.22,3.75,1-6 7-6 2-6
2,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Loit E.,Birnerova E.,Loit E.,56,84,418,324,1.72,2,6-1 6-1
3,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,1.83,1.83,5-7 2-6
4,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,1.16,4.5,7-6 6-3

In [ ]:
# Esta es la otra opción que creo que no usaré. Un csv por año. 
# Tiene muchos datos de estadísticos de partidos. Pero solo está hasta 2004
stats_2024= pd.read_csv(r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta_matches_2024.csv")
stats_2024.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-9900,United Cup,Hard,18,I,20240101,299,216347,NaN,NaN,...,27.0,13.0,7.0,7.0,4.0,8.0,1.0,9505.0,NaN,NaN
1,2024-9900,United Cup,Hard,18,I,20240101,297,216347,NaN,NaN,...,47.0,28.0,7.0,12.0,3.0,8.0,1.0,9505.0,20.0,2330.0
2,2024-9900,United Cup,Hard,18,I,20240101,295,201493,NaN,NaN,...,82.0,47.0,10.0,15.0,11.0,19.0,NaN,NaN,292.0,246.0
3,2024-9900,United Cup,Hard,18,I,20240101,293,216347,NaN,NaN,...,27.0,18.0,6.0,8.0,6.0,11.0,1.0,9505.0,14.0,2770.0
4,2024-9900,United Cup,Hard,18,I,20240101,291,201614,NaN,NaN,...,72.0,51.0,22.0,16.0,3.0,6.0,20.0,2330.0,544.0,89.0