In [1]:
import pandas as pd

In [2]:
wta = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta.csv", low_memory= False)

In [3]:
wta.head()

,Tournament,Date,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,1.33,3,6-1 6-1
1,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,1.22,3.75,1-6 7-6 2-6
2,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Loit E.,Birnerova E.,Loit E.,56,84,418,324,1.72,2,6-1 6-1
3,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,1.83,1.83,5-7 2-6
4,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,1.16,4.5,7-6 6-3

In [4]:
wta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44353 entries, 0 to 44352
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  44353 non-null  object
 1   Date        44353 non-null  object
 2   Court       44353 non-null  object
 3   Surface     44353 non-null  object
 4   Round       44353 non-null  object
 5   Best of     44353 non-null  int64
 6   Player_1    44353 non-null  object
 7   Player_2    44353 non-null  object
 8   Winner      44353 non-null  object
 9   Rank_1      44353 non-null  int64
 10  Rank_2      44353 non-null  int64
 11  Pts_1       44353 non-null  int64
 12  Pts_2       44353 non-null  int64
 13  Odd_1       44353 non-null  object
 14  Odd_2       44353 non-null  object
 15  Score       44353 non-null  object
dtypes: int64(5), object(11)
memory usage: 5.4+ MB

In [5]:
stats_2024= pd.read_csv(r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta_matches_2024.csv")

In [6]:
stats_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2689 entries, 0 to 2688
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          2689 non-null   object
 1   tourney_name        2689 non-null   object
 2   surface             2632 non-null   object
 3   draw_size           2689 non-null   int64
 4   tourney_level       2689 non-null   object
 5   tourney_date        2689 non-null   int64
 6   match_num           2689 non-null   int64
 7   winner_id           2689 non-null   int64
 8   winner_seed         1132 non-null   float64
 9   winner_entry        454 non-null    object
 10  winner_name         2689 non-null   object
 11  winner_hand         2689 non-null   object
 12  winner_ht           2001 non-null   float64
 13  winner_ioc          2689 non-null   object
 14  winner_age          2689 non-null   float64
 15  loser_id            2689 non-null   int64
 16  loser_seed          682 non-null    float64
 17  loser_entry         727 non-null    object
 18  loser_name          2689 non-null   object
 19  loser_hand          2689 non-null   object
 20  loser_ht            1886 non-null   float64
 21  loser_ioc           2689 non-null   object
 22  loser_age           2687 non-null   float64
 23  score               2689 non-null   object
 24  best_of             2689 non-null   int64
 25  round               2689 non-null   object
 26  minutes             2396 non-null   float64
 27  w_ace               2624 non-null   float64
 28  w_df                2624 non-null   float64
 29  w_svpt              2624 non-null   float64
 30  w_1stIn             2624 non-null   float64
 31  w_1stWon            2624 non-null   float64
 32  w_2ndWon            2624 non-null   float64
 33  w_SvGms             2624 non-null   float64
 34  w_bpSaved           2624 non-null   float64
 35  w_bpFaced           2624 non-null   float64
 36  l_ace               2624 non-null   float64
 37  l_df                2624 non-null   float64
 38  l_svpt              2624 non-null   float64
 39  l_1stIn             2624 non-null   float64
 40  l_1stWon            2624 non-null   float64
 41  l_2ndWon            2624 non-null   float64
 42  l_SvGms             2624 non-null   float64
 43  l_bpSaved           2624 non-null   float64
 44  l_bpFaced           2624 non-null   float64
 45  winner_rank         2686 non-null   float64
 46  winner_rank_points  2686 non-null   float64
 47  loser_rank          2674 non-null   float64
 48  loser_rank_points   2674 non-null   float64
dtypes: float64(29), int64(6), object(14)
memory usage: 1.0+ MB

In [7]:
stats_2024.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-9900,United Cup,Hard,18,I,20240101,299,216347,NaN,NaN,...,27.0,13.0,7.0,7.0,4.0,8.0,1.0,9505.0,NaN,NaN
1,2024-9900,United Cup,Hard,18,I,20240101,297,216347,NaN,NaN,...,47.0,28.0,7.0,12.0,3.0,8.0,1.0,9505.0,20.0,2330.0
2,2024-9900,United Cup,Hard,18,I,20240101,295,201493,NaN,NaN,...,82.0,47.0,10.0,15.0,11.0,19.0,NaN,NaN,292.0,246.0
3,2024-9900,United Cup,Hard,18,I,20240101,293,216347,NaN,NaN,...,27.0,18.0,6.0,8.0,6.0,11.0,1.0,9505.0,14.0,2770.0
4,2024-9900,United Cup,Hard,18,I,20240101,291,201614,NaN,NaN,...,72.0,51.0,22.0,16.0,3.0,6.0,20.0,2330.0,544.0,89.0