# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [43]:
chipo ["item_name"] [chipo ["item_price"].idxmax()]

'Steak Salad Bowl'

### Step 4. How many products cost more than $10.00?

In [44]:
# Había hecho esto pero no lo estaba haciendo bien
#chipo ["item_price"] = chipo ["item_price"].str.replace ("$","").astype(float) 

# Así que he copiado de chatgpt
chipo["item_price"] = (
    chipo["item_price"]
    .str.replace("$", "", regex=False)  # quita el $
    .astype(float)                       # convierte a float
)

#chipo ["item_name"][chipo["item_price"] > 10.00].value_counts() 
#nunique devuelve número de elementos únicos
chipo [chipo["item_price"] > 10.00] ["item_name"].nunique()

31

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [45]:
# No es lo mismo. Cada pedido tiene varias líneas
chipo [chipo["item_price"] > 10]["order_id"].nunique()

863

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [46]:
# Tampoco es lo mismo. Cada producto en cada pedido es una línea. Habría que multiplicar item_price x quantity
# de todos los productos del mismo id y sumarlos

chipo ["total_prize"] = chipo ["quantity"]*chipo["item_price"]
#chipo.groupby?

totales_pedido = chipo.groupby(["order_id"])["total_prize"].sum()
totales_pedido [totales_pedido > 10].nunique()

446

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [47]:
# En total_prize está el precio total de cada producto en cada pedido

chipo[chipo["total_prize"]>10]["order_id"].nunique()

889

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [4]:
#chipo ["item_price"].rename ("unit_price") MAL
chipo.rename (columns = {"item_price": "unit_price"}, inplace = True)
items_prices = chipo.loc [:,["item_name","unit_price"]]
items_prices

                                  item_name unit_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
4                              Chicken Bowl    $16.98
...                                     ...        ...
4617                          Steak Burrito    $11.75
4618                          Steak Burrito    $11.75
4619                     Chicken Salad Bowl    $11.25
4620                     Chicken Salad Bowl     $8.75
4621                     Chicken Salad Bowl     $8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [6]:
items_prices.sort_values (by="item_name").drop_duplicates (["item_name"])

                                  item_name unit_price
3389                      6 Pack Soft Drink    $12.98
418                           Barbacoa Bowl     $9.25
1202                       Barbacoa Burrito    $11.75
1019                  Barbacoa Crispy Tacos     $8.99
3546                    Barbacoa Salad Bowl    $11.89
3548                    Barbacoa Soft Tacos    $11.75
2441                          Bottled Water     $7.50
673                                    Bowl     $7.40
760                                 Burrito     $7.40
1142                            Canned Soda     $1.09
964                       Canned Soft Drink     $1.25
1359                          Carnitas Bowl     $8.99
1097                       Carnitas Burrito    $11.75
554                   Carnitas Crispy Tacos     $9.25
3750                         Carnitas Salad     $8.99
2610                    Carnitas Salad Bowl    $11.89
2299                    Carnitas Soft Tacos     $9.25
4555                           Chicken Bowl     $8.75
2026                        Chicken Burrito     $8.75
1027                   Chicken Crispy Tacos    $10.98
2968                          Chicken Salad     $8.49
3117                     Chicken Salad Bowl     $8.75
1496                     Chicken Soft Tacos     $8.49
2193                                  Chips     $2.15
3506           Chips and Fresh Tomato Salsa     $2.39
311                     Chips and Guacamole     $4.45
674       Chips and Mild Fresh Tomato Salsa     $3.00
2602     Chips and Roasted Chili Corn Salsa     $2.95
1458     Chips and Roasted Chili-Corn Salsa     $2.39
1593  Chips and Tomatillo Green Chili Salsa     $2.95
1999    Chips and Tomatillo Red Chili Salsa     $2.95
3657  Chips and Tomatillo-Green Chili Salsa     $4.78
2972    Chips and Tomatillo-Red Chili Salsa     $7.17
521                            Crispy Tacos     $7.40
1213                                   Izze     $3.39
2379                       Nantucket Nectar     $6.78
1414                                  Salad     $7.40
1120                          Side of Chips     $1.69
3190                             Steak Bowl    $11.75
4546                          Steak Burrito     $9.25
3503                     Steak Crispy Tacos     $9.25
752                             Steak Salad     $8.99
4391                       Steak Salad Bowl     $9.39
4549                       Steak Soft Tacos     $9.25
2326                            Veggie Bowl     $8.75
1959                         Veggie Burrito    $11.25
1653                    Veggie Crispy Tacos     $8.49
3471                           Veggie Salad     $8.49
4201                      Veggie Salad Bowl    $11.25
738                       Veggie Soft Tacos    $11.25

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [13]:
#Encontrar el producto más caro y sumar todas sus quantitys
# totales_pedido = chipo.groupby(["order_id"])["total_prize"].sum()
#Esta mal porque no es steak salad bowl
most_expensive = chipo.loc[chipo ["unit_price"].idxmax(), "item_name"]

chipo[chipo["item_name"] == most_expensive]["quantity"].sum()

np.int64(31)

### Step 8. How many times was a Veggie Salad Bowl ordered?

### Step 9. How many times did someone order more than one Canned Soda?