In [1]:
import pandas as pd

In [13]:
oscars = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_cine\Oscar_Awards.csv", sep="\t")
print(oscars.shape)
oscars.info()

(12014, 16)
<class 'pandas.DataFrame'>
RangeIndex: 12014 entries, 0 to 12013
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ceremony             12014 non-null  int64
 1   Year                 12014 non-null  str
 2   Class                12014 non-null  str
 3   CanonicalCategory    12014 non-null  str
 4   Category             12014 non-null  str
 5   NomId                11482 non-null  str
 6   Film                 10753 non-null  str
 7   FilmId               10753 non-null  str
 8   Name                 10829 non-null  str
 9   Nominees             11661 non-null  str
 10  NomineeIds           11134 non-null  str
 11  Winner               3476 non-null   object
 12  Detail               3171 non-null   str
 13  Note                 616 non-null    str
 14  Citation             1183 non-null   str
 15  MultifilmNomination  40 non-null     object
dtypes: int64(1), object(2), str(13)
memory usage: 1.5+ MB

In [9]:
oscars.tail(5)

,Ceremony,Year,Class,CanonicalCategory,Category,NomId,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation,MultifilmNomination
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Dustin Brooks, Colin Decker",NaN,True,NaN,Fire for Hire's gel first publicly demonstrate...,To DUSTIN BROOKS and COLIN DECKER for the deve...,NaN
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Attila T. Áfra, Timo Aila",NaN,True,NaN,Open Image Denoise is an open-source library t...,To ATTILA T. ÁFRA for the creation of Intel Op...,NaN
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Mark Noel,NaN,True,NaN,The NACMO series of modular motion bases enabl...,To MARK NOEL for adapting and enhancing the sa...,NaN
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Su Tie, Bei Shimen, Zhao Yanchong",NaN,True,NaN,Utilizing three-axis stabilization through mul...,To SU TIE for the development of the sensor an...,NaN
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Tabb Firchau, John Ellison, Steve Webb, David ...",NaN,True,NaN,Freefly Systems' introduction of handheld stab...,To TABB FIRCHAU for the conception and develop...,NaN

In [20]:
oscars[(oscars["Class"] == "Acting") & (oscars["Year"]=="2024")].shape

(20, 16)

In [15]:
oscars["Class"].unique()

<StringArray>
[    'Acting', 'Production',  'Directing',      'Title',    'Writing',
    'Special',    'SciTech',      'Music']
Length: 8, dtype: str

In [16]:
oscars[(oscars["Class"] == "Directing") & (oscars["Year"]=="2024")]

,Ceremony,Year,Class,CanonicalCategory,Category,NomId,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation,MultifilmNomination
11916,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid032,Anora,tt28607951,Sean Baker,Sean Baker,nm0048918,True,NaN,NaN,NaN,NaN
11917,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid030,The Brutalist,tt8999762,Brady Corbet,Brady Corbet,nm1227232,NaN,NaN,NaN,NaN,NaN
11918,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid034,A Complete Unknown,tt11563598,James Mangold,James Mangold,nm0003506,NaN,NaN,NaN,NaN,NaN
11919,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid031,Emilia Pérez,tt20221436,Jacques Audiard,Jacques Audiard,nm0002191,NaN,NaN,NaN,NaN,NaN
11920,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid033,The Substance,tt17526714,Coralie Fargeat,Coralie Fargeat,nm0267287,NaN,NaN,NaN,NaN,NaN

In [21]:
acting = oscars[oscars["Class"] == "Acting"]
acting.shape

(1855, 16)

In [ ]:
imdb = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_cine\name.basics.tsv\name.basics.tsv", sep="\t")
imdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 15178050 entries, 0 to 15178049
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   nconst             str
 1   primaryName        str
 2   birthYear          str
 3   deathYear          str
 4   primaryProfession  str
 5   knownForTitles     str
dtypes: str(6)
memory usage: 694.8 MB

In [25]:
imdb.head(5)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"