In [2]:
import pandas as pd

In [2]:
add_vivienda = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_vivienda\addinfo.csv")

In [ ]:
add_vivienda.info()

<class 'pandas.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   poblacion  106 non-null    str
 1   source     106 non-null    str
 2   valor      106 non-null    str
dtypes: str(3)
memory usage: 2.6 KB

In [4]:
add_vivienda.head(5)

             poblacion    source      valor
0       Total Nacional  Empresas  3.337.646
1          02 Albacete  Empresas     26.743
2  03 Alicante/Alacant  Empresas    138.964
3           04 Almería  Empresas     42.931
4       01 Araba/Álava  Empresas     19.147

In [6]:
madrid = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_vivienda\houses_madrid.csv")

In [7]:
madrid.info()

<class 'pandas.DataFrame'>
RangeIndex: 5255 entries, 0 to 5254
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ad_description     5184 non-null   str
 1   ad_last_update     5255 non-null   str
 2   air_conditioner    5255 non-null   str
 3   balcony            5255 non-null   str
 4   bath_num           5255 non-null   str
 5   built_in_wardrobe  5255 non-null   str
 6   chimney            5255 non-null   str
 7   condition          5003 non-null   str
 8   construct_date     2252 non-null   str
 9   energetic_certif   3990 non-null   str
 10  floor              5135 non-null   str
 11  garage             1829 non-null   str
 12  garden             5255 non-null   str
 13  ground_size        7 non-null      str
 14  heating            2857 non-null   str
 15  house_id           5255 non-null   str
 16  house_type         5255 non-null   str
 17  kitchen            7 non-null      str
 18  lift               4873 non-null   str
 19  loc_city           5255 non-null   str
 20  loc_district       5255 non-null   str
 21  loc_full           5255 non-null   str
 22  loc_neigh          5153 non-null   str
 23  loc_street         3890 non-null   str
 24  loc_zone           5255 non-null   str
 25  m2_real            5255 non-null   str
 26  m2_useful          2281 non-null   str
 27  obtention_date     5255 non-null   str
 28  orientation        2438 non-null   str
 29  price              5255 non-null   str
 30  reduced_mobility   5255 non-null   str
 31  room_num           5255 non-null   str
 32  storage_room       5255 non-null   str
 33  swimming_pool      5255 non-null   str
 34  terrace            5255 non-null   str
 35  unfurnished        7 non-null      str
dtypes: str(36)
memory usage: 1.4 MB

In [8]:
madrid.head(5)

,ad_description,ad_last_update,air_conditioner,balcony,bath_num,built_in_wardrobe,chimney,condition,construct_date,energetic_certif,...,m2_useful,obtention_date,orientation,price,reduced_mobility,room_num,storage_room,swimming_pool,terrace,unfurnished
0,"Particular vende piso de 103 m² en Pinto, prov...",Anuncio actualizado el 10 de abril,1,0,1,0,0,segunda mano/buen estado,1976,en trámite,...,96,2019-04-12,NaN,164900,0,3,0,0,1,NaN
1,"El suelo de la planta superior es de tarima, l...",más de 5 meses sin actualizar,1,0,2,1,0,segunda mano/buen estado,NaN,no indicado,...,NaN,2019-04-12,NaN,370000,0,4,1,0,1,NaN
2,NaN,más de 5 meses sin actualizar,0,0,2,0,0,segunda mano/buen estado,NaN,no indicado,...,NaN,2019-04-12,NaN,190000,0,3,0,0,0,NaN
3,NaN,más de 5 meses sin actualizar,1,0,3,1,0,segunda mano/buen estado,NaN,NaN,...,215,2019-04-12,"norte, sur",450000,0,4,1,1,1,NaN
4,Parque Europa. Plaza David Martín junto ambula...,más de 5 meses sin actualizar,1,0,2,1,0,segunda mano/buen estado,2000,no indicado,...,100,2019-04-12,"sur, este",282000,1,4,1,0,1,NaN

In [3]:
#Qué son estos
dataset39363 = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_vivienda\39363.csv", sep=";")
dataset39363.head(5)

,Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Municipios,Viviendas y plazas,Periodo,Total
0,Total Nacional,NaN,NaN,NaN,Viviendas turísticas,2025M11,329.764
1,Total Nacional,NaN,NaN,NaN,Viviendas turísticas,2025M05,381.837
2,Total Nacional,NaN,NaN,NaN,Viviendas turísticas,2024M11,376.463
3,Total Nacional,NaN,NaN,NaN,Viviendas turísticas,2024M08,403.267
4,Total Nacional,NaN,NaN,NaN,Viviendas turísticas,2024M02,351.389

In [4]:
#Numero de viviendas turísticas por municipio desde Ago 2020 a Nov 2025
dataset39363.info()
#madrid= dataset39363.loc[dataset39363 ["Municipios" == "madrid"]]
dataset39363 ["Periodo"].nunique()
dataset39363 ["Periodo"].values
dataset39363 ["Periodo"].min()
dataset39363 ["Periodo"].max()




#dataset39363 ["Provincias"].values

<class 'pandas.DataFrame'>
RangeIndex: 295452 entries, 0 to 295451
Data columns (total 7 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Total Nacional                    295452 non-null  str
 1   Comunidades y Ciudades Autónomas  295416 non-null  str
 2   Provincias                        294732 non-null  str
 3   Municipios                        292860 non-null  str
 4   Viviendas y plazas                295452 non-null  str
 5   Periodo                           295452 non-null  str
 6   Total                             272708 non-null  str
dtypes: str(7)
memory usage: 15.8 MB

'2025M11'

In [1]:
#Porcentaje de viviendas turísticas sobre el total de vivienda censada por municipios. General. No hay barrios
dataset39366 = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_vivienda\39366.csv", sep=";")
dataset39366.tail(5)

NameError: name 'pd' is not defined

In [32]:
min=dataset39363["Periodo"].min()
max=dataset39363["Periodo"].max()
print (min,max)
print(dataset39363.shape)

2020M08 2025M11
(295452, 7)

In [ ]:
# Población por municipio de 2021 a 2025
dataset67991 = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_vivienda\67991.csv", sep=";")
dataset67991.head(5)
min = dataset67991 ["Periodo"].min()
max = dataset67991 ["Periodo"].max()
print (min, max)

2021 2025

In [30]:
airbnb = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_vivienda\airbnb_madrid_listings.csv")
airbnb.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              25000 non-null  int64
 1   name                            25000 non-null  str
 2   host_id                         25000 non-null  int64
 3   host_name                       24903 non-null  str
 4   neighbourhood_group             25000 non-null  str
 5   neighbourhood                   25000 non-null  str
 6   latitude                        25000 non-null  float64
 7   longitude                       25000 non-null  float64
 8   room_type                       25000 non-null  str
 9   price                           18953 non-null  float64
 10  minimum_nights                  25000 non-null  int64
 11  number_of_reviews               25000 non-null  int64
 12  last_review                     19853 non-null  str
 13  reviews_per_month               19853 non-null  float64
 14  calculated_host_listings_count  25000 non-null  int64
 15  availability_365                25000 non-null  int64
 16  number_of_reviews_ltm           25000 non-null  int64
 17  license                         9188 non-null   str
dtypes: float64(4), int64(7), str(7)
memory usage: 3.4 MB