In [8]:
import pandas as pd

In [13]:
oscars = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_cine\Oscar_Awards.csv", sep="\t")
print(oscars.shape)
oscars.info()

(12014, 16)
<class 'pandas.DataFrame'>
RangeIndex: 12014 entries, 0 to 12013
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ceremony             12014 non-null  int64
 1   Year                 12014 non-null  str
 2   Class                12014 non-null  str
 3   CanonicalCategory    12014 non-null  str
 4   Category             12014 non-null  str
 5   NomId                11482 non-null  str
 6   Film                 10753 non-null  str
 7   FilmId               10753 non-null  str
 8   Name                 10829 non-null  str
 9   Nominees             11661 non-null  str
 10  NomineeIds           11134 non-null  str
 11  Winner               3476 non-null   object
 12  Detail               3171 non-null   str
 13  Note                 616 non-null    str
 14  Citation             1183 non-null   str
 15  MultifilmNomination  40 non-null     object
dtypes: int64(1), object(2), str(13)
memory usage: 1.5+ MB

In [9]:
oscars.tail(5)

,Ceremony,Year,Class,CanonicalCategory,Category,NomId,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation,MultifilmNomination
12009,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Dustin Brooks, Colin Decker",NaN,True,NaN,Fire for Hire's gel first publicly demonstrate...,To DUSTIN BROOKS and COLIN DECKER for the deve...,NaN
12010,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Attila T. Áfra, Timo Aila",NaN,True,NaN,Open Image Denoise is an open-source library t...,To ATTILA T. ÁFRA for the creation of Intel Op...,NaN
12011,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,Mark Noel,NaN,True,NaN,The NACMO series of modular motion bases enabl...,To MARK NOEL for adapting and enhancing the sa...,NaN
12012,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Su Tie, Bei Shimen, Zhao Yanchong",NaN,True,NaN,Utilizing three-axis stabilization through mul...,To SU TIE for the development of the sensor an...,NaN
12013,97,2024,SciTech,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,SCIENTIFIC AND TECHNICAL AWARD (Technical Achi...,NaN,NaN,NaN,NaN,"Tabb Firchau, John Ellison, Steve Webb, David ...",NaN,True,NaN,Freefly Systems' introduction of handheld stab...,To TABB FIRCHAU for the conception and develop...,NaN

In [20]:
oscars[(oscars["Class"] == "Acting") & (oscars["Year"]=="2024")].shape

(20, 16)

In [15]:
oscars["Class"].unique()

<StringArray>
[    'Acting', 'Production',  'Directing',      'Title',    'Writing',
    'Special',    'SciTech',      'Music']
Length: 8, dtype: str

In [16]:
oscars[(oscars["Class"] == "Directing") & (oscars["Year"]=="2024")]

,Ceremony,Year,Class,CanonicalCategory,Category,NomId,Film,FilmId,Name,Nominees,NomineeIds,Winner,Detail,Note,Citation,MultifilmNomination
11916,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid032,Anora,tt28607951,Sean Baker,Sean Baker,nm0048918,True,NaN,NaN,NaN,NaN
11917,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid030,The Brutalist,tt8999762,Brady Corbet,Brady Corbet,nm1227232,NaN,NaN,NaN,NaN,NaN
11918,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid034,A Complete Unknown,tt11563598,James Mangold,James Mangold,nm0003506,NaN,NaN,NaN,NaN,NaN
11919,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid031,Emilia Pérez,tt20221436,Jacques Audiard,Jacques Audiard,nm0002191,NaN,NaN,NaN,NaN,NaN
11920,97,2024,Directing,DIRECTING,DIRECTING,fake_nomid033,The Substance,tt17526714,Coralie Fargeat,Coralie Fargeat,nm0267287,NaN,NaN,NaN,NaN,NaN

In [21]:
acting = oscars[oscars["Class"] == "Acting"]
acting.shape

(1855, 16)

In [ ]:
imdb = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\2026-02-BILBAO-FT-Data-Science\2-Data_Analysis\EDA\data_cine\name.basics.tsv\name.basics.tsv", sep="\t")
imdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 15178050 entries, 0 to 15178049
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   nconst             str
 1   primaryName        str
 2   birthYear          str
 3   deathYear          str
 4   primaryProfession  str
 5   knownForTitles     str
dtypes: str(6)
memory usage: 694.8 MB

In [25]:
imdb.head(5)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [3]:
tmdb =pd.read_csv(r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos EDA\data_cine\tmdb_5000_credits.csv")

In [4]:
tmdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 150.2 KB

In [9]:
mojo = pd.read_csv(r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos EDA\data_cine\Mojo_budget_update.csv")

In [6]:
mojo.info()

<class 'pandas.DataFrame'>
RangeIndex: 3243 entries, 0 to 3242
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   movie_id         3243 non-null   str
 1   title            3243 non-null   str
 2   year             3243 non-null   int64
 3   trivia           3243 non-null   str
 4   mpaa             3082 non-null   str
 5   release_date     3242 non-null   str
 6   run_time         3243 non-null   str
 7   distributor      3228 non-null   str
 8   director         3243 non-null   str
 9   writer           3234 non-null   str
 10  producer         3230 non-null   str
 11  composer         3138 non-null   str
 12  cinematographer  3129 non-null   str
 13  main_actor_1     3243 non-null   str
 14  main_actor_2     3243 non-null   str
 15  main_actor_3     3243 non-null   str
 16  main_actor_4     3240 non-null   str
 17  budget           3243 non-null   float64
 18  domestic         3224 non-null   float64
 19  international    2833 non-null   float64
 20  worldwide        3236 non-null   float64
 21  genre_1          3243 non-null   str
 22  genre_2          2962 non-null   str
 23  genre_3          2221 non-null   str
 24  genre_4          1123 non-null   str
 25  html             3243 non-null   str
dtypes: float64(4), int64(1), str(21)
memory usage: 658.9 KB

In [7]:
mojo.head(5)

,movie_id,title,year,trivia,mpaa,release_date,run_time,distributor,director,writer,...,main_actor_4,budget,domestic,international,worldwide,genre_1,genre_2,genre_3,genre_4,html
0,tt0099088,Back to the Future Part III,1990,"Stranded in 1955, Marty McFly learns about the...",NaN,May 25,1 hr 58 min,Universal Pictures,Robert Zemeckis,Robert Zemeckis,...,Thomas F. Wilson,40000000.0,88277583.0,157866667.0,246144250.0,Adventure,Comedy,Sci-Fi,Western,https://www.boxofficemojo.com/title/tt0099088/...
1,tt0099165,The Bonfire of the Vanities,1990,"After his mistress runs over a young teen, a W...",R,December 22,2 hr 5 min,Warner Bros.,Brian De Palma,Michael Cristofer,...,Kim Cattrall,47000000.0,15691192.0,NaN,15691192.0,Comedy,Drama,Romance,NaN,https://www.boxofficemojo.com/title/tt0099165/...
2,tt0099348,Dances with Wolves,1990,"Lieutenant John Dunbar, assigned to a remote w...",NaN,November 9,3 hr 1 min,Orion Pictures,Kevin Costner,Michael Blake,...,Rodney A. Grant,22000000.0,184208848.0,240000000.0,424208848.0,Adventure,Drama,Western,NaN,https://www.boxofficemojo.com/title/tt0099348/...
3,tt0099422,Dick Tracy,1990,The comic strip detective finds his life vastl...,NaN,June 15,1 hr 45 min,Walt Disney Studios Motion Pictures,Warren Beatty,Chester Gould,...,Charlie Korsmo,47000000.0,103738726.0,59000000.0,162738726.0,Action,Comedy,Crime,Music,https://www.boxofficemojo.com/title/tt0099422/...
4,tt0099423,Die Hard 2,1990,John McClane attempts to avert disaster as rog...,NaN,July 6,2 hr 4 min,Twentieth Century Fox,Renny Harlin,Walter Wager,...,Reginald VelJohnson,70000000.0,117540947.0,122706486.0,240247433.0,Action,Thriller,NaN,NaN,https://www.boxofficemojo.com/title/tt0099423/...

In [10]:
mojo.columns

Index(['movie_id', 'title', 'year', 'trivia', 'mpaa', 'release_date',
       'run_time', 'distributor', 'director', 'writer', 'producer', 'composer',
       'cinematographer', 'main_actor_1', 'main_actor_2', 'main_actor_3',
       'main_actor_4', 'budget', 'domestic', 'international', 'worldwide',
       'genre_1', 'genre_2', 'genre_3', 'genre_4', 'html'],
      dtype='str')

In [33]:
mojo["year"].max()

np.int64(2020)

In [12]:
tmdb = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos EDA\data_cine\tmdb_5000_movies.csv")

In [13]:
tmdb.shape

(4803, 20)

In [14]:
tmdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 750.6 KB

In [15]:
tmdb.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [19]:
tmdb_credits = pd.read_csv(r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos EDA\data_cine\tmdb_5000_credits.csv")

In [20]:
tmdb_credits.shape

(4803, 4)

In [ ]:
tmdb_credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 150.2 KB

In [22]:
tmdb_credits.tail(5)

,movie_id,title,cast,crew
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [26]:
tmdb[tmdb ["original_language"] =="es"]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
492,8000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 16, ""nam...",NaN,293644,"[{""id"": 209714, ""name"": ""3d""}]",es,Don Gato: El inicio de la pandilla,Top Cat has arrived to charm his way into your...,0.719996,"[{""name"": ""Anima Estudios"", ""id"": 9965}, {""nam...","[{""iso_3166_1"": ""IN"", ""name"": ""India""}, {""iso_...",2015-10-30,0,89.0,[],Released,NaN,Top Cat Begins,5.3,9
1462,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,45958,"[{""id"": 2356, ""name"": ""immigrant""}, {""id"": 124...",es,Biutiful,This is a story of a man in free fall. On the ...,13.930763,"[{""name"": ""Ikiru Films"", ""id"": 2875}, {""name"":...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",2010-10-20,25147786,148.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,You don't choose your family. We all belong to...,Biutiful,7.0,291
1463,35000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",NaN,1969,"[{""id"": 534, ""name"": ""mexico""}, {""id"": 2492, ""...",es,Bandidas,Set in the late 19th century. When a ruthless ...,20.277040,"[{""name"": ""Ultra Films"", ""id"": 828}, {""name"": ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-01-18,10496317,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Being BAD never looked so GOOD!,Bandidas,5.8,307
1741,24000000,"[{""id"": 28, ""name"": ""Action""}]",NaN,13495,[],es,Alatriste,"In 17th century Spain Diego Alatriste, a brave...",6.009644,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2006-09-01,23321954,145.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,Alatriste,5.6,61
2064,22000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 12, ""...",NaN,153158,"[{""id"": 13042, ""name"": ""soccer""}]",es,Metegol,In the small village where Amadeo lives there ...,14.866351,"[{""name"": ""100 Bares"", ""id"": 5517}, {""name"": ""...","[{""iso_3166_1"": ""AR"", ""name"": ""Argentina""}, {""...",2013-07-18,24000000,106.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,There's only one team this summer.,Underdogs,6.0,122
2465,19000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 18, ""na...",http://www.panslabyrinth.com,1417,"[{""id"": 514, ""name"": ""spain""}, {""id"": 836, ""na...",es,El laberinto del fauno,Living with her tyrannical stepfather in a new...,90.809408,"[{""name"": ""Estudios Picasso"", ""id"": 2029}, {""n...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}, {""iso_...",2006-05-27,83258226,118.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,What happens when make-believe believes it's r...,Pan's Labyrinth,7.6,3041
2512,0,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 35, ""...",NaN,12154,"[{""id"": 1009, ""name"": ""baby""}, {""id"": 1253, ""n...",es,Three Men and a Baby,Three bachelors find themselves forced to take...,12.335827,"[{""name"": ""Touchstone Pictures"", ""id"": 9195}, ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1987-11-27,0,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,They changed her diapers. She changed their li...,Three Men and a Baby,5.8,253
2725,12806000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,1913,"[{""id"": 380, ""name"": ""brother brother relation...",es,Mar adentro,The Sea Inside is about Spaniard Ramón Sampedr...,17.363739,"[{""name"": ""Canal Plus"", ""id"": 104}, {""name"": ""...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}, {""iso_...",2004-09-03,38535221,125.0,"[{""iso_639_1"": ""gl"", ""name"": ""Galego""}, {""iso_...",Released,Sensitive Drama About a Polemic Theme,The Sea Inside,7.2,219
3113,10000000,"[{""id"": 10752, ""name"": ""War""}, {""id"": 36, ""nam...",http://www.facebook.com/CincodeMayo.LaPelicula,184374,"[{""id"": 163127, ""name"": ""mexican""}]",es,Cinco de Mayo: La Batalla,"On May 5th, 1862, a few thousand Mexican soldi...",0.072085,"[{""name"": ""Estudios Churubusco Azteca"", ""id"": ...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2013-05-03,0,125.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,NaN,Cinco de Mayo: La Batalla,5.8,14
3149,12899867,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.volver-lapelicula.com,219,"[{""id"": 516, ""name"": ""child abuse""}, {""id"": 57...",es,Volver,Raimunda (Penélope Cruz) works and lives Madri...,19.747809,"[{""name"": ""El Deseo"", ""id"": 49}]","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2006-03-16,85582407,121.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Return.,Volver,7.3,406
3524,5600000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",http://www.rec2themovie.com/,10664,"[{""id"": 3684, ""name"": ""religion and supernatur...",es,[REC]²,"The action continues from [REC], with the medi...",22.341462,"[{""name"": ""Filmax"", ""id"": 3631}]","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2009-09-15,18469680,85.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Fear Revisited,[REC]²,6.4,489
3562,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,211954,"[{""id"": 1338, ""name"": ""bachelor""}, {""id"": 1554...",es,No se Aceptan Devoluciones,"Valentin is Acapulco's resident playboy, until...",9.597290,"[{""name"": ""Filmax"", ""id"": 3631}, {""name"": ""Sig...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2013-07-20,99067206,115.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,Life doesn't care if you're ready.,Instructions Not Included,7.5,205
3596,5000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",NaN,1391,"[{""id"": 534, ""name"": ""mexico""}, {""id"": 572, ""n...",es,Y tu mamá también,"In Mexico, two teenage boys and an attractive ...",16.890285,"[{""name"": ""B\u00e9same Mucho Pictures"", ""id"": ...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2001-06-08,33616692,106.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Life has its ways of teaching. Life has its wa...,Y Tu Mamá También,7.3,315
3657,5000000,"[{""id"": 53, ""name"": ""Thriller""}]",http://www.mientrasduermeslapelicula.com/,77495,"[{""id"": 107, ""name"": ""barcelona spain""}, {""id""...",es,Mientras duermes,Apartment concierge Cesar is a miserable perso...,9.136965,"[{""name"": ""Filmax Entertainment"", ""id"": 7302},...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2011-10-14,0,107.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Someone is watching over you,Sleep Tight,7.0,202
3703,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",NaN,65749,"[{""id"": 733, ""name"": ""dancer""}, {""id"": 2683, ""...",es,"Tango, no me dejes nunca",A dangerous love affair inspires a director to...,0.425551,"[{""name"": ""Adela Pictures"", ""id"": 40451}]","[{""iso_3166_1"": ""AR"", ""name"": ""Argentina""}, {""...",1998-02-12,0,115.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Tango: do not ever leave me,Tango,6.8,6
3761,0,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...",NaN,6537,"[{""id"": 222, ""name"": ""schizophrenia""}, {""id"": ...",es,El orfanato,A woman brings her family back to her childhoo...,29.071955,"[{""name"": ""Wild Bunch"", ""id"": 856}, {""name"": ""...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}, {""iso_...",2007-08-27,44000000,105.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,A tale of love. A story of horror.,The Orphanage,7.1,633
3794,4000000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,54580,"[{""id"": 514, ""name"": ""spain""}, {""id"": 1010, ""n...",es,Los lunes al sol,After the closure of their shipyard in Norther...,3.663108,"[{""name"": ""V\u00eda Digital"", ""id"": 357}, {""na...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}, {""iso_...",2002-09-27,146402,113.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,This film is not based on a real story. It is ...,Mondays in the Sun,7.1,36
3839,2000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.elsecretodesusojos.com,25376,"[{""id"": 570, ""name"": ""rape""}, {""id"": 1328, ""na...",es,El secreto de sus ojos,A retired legal counselor writes a novel hopin...,25.894065,"[{""name"": ""100 Bares"", ""id"": 5517}, {""name"": ""...","[{""iso_3166_1"": ""AR"", ""name"": ""Argentina""}, {""...",2009-08-13,33965843,129.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,The Secret in Their Eyes,7.8,626
3844,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",NaN,89540,"[{""id"": 293, ""name"": ""female nudity""}, {""id"": ...",es,La otra conquista,The film is a drama about the aftermath of the...,0.015597,[],"[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",1999-04-01,0,105.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,The spirit of a people can never be conquered.,The Other Conquest,5.4,4
3880,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",http://www.mariallenaeresdegracia.com/index.html,436,"[{""id"": 30, ""name"": ""individual""}, {""id"": 242,...",es,"María, llena eres de gracia",A pregnant Colombian teenager becomes a drug m...,3.027892,"[{""name"": ""Fine Line Features"", ""id"": 8}, {""na...","[{""iso_3166_1"": ""EC"", ""name"": ""Ecuador""}, {""is...",2004-01-18,0,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Based on 10,000 true stories.",Maria Full of Grace,6.9,101
3943,3000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://genvideoshd.com/watch-compadres-2016-fu...,317930,[],es,Compadres,A disgruntled Mexican cop is forced to work wi...,1.569246,[],[],2016-03-31,0,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Compadres,5.2,17
4003,2600000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.cronocrimenes.com/,14139,"[{""id"": 1435, ""name"": ""scissors""}, {""id"": 2135...",es,Los cronocrímenes,A man accidentally gets into a time machine an...,19.029650,"[{""name"": ""Ars\u00e9nico Producciones"", ""id"": ...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2007-09-20,553198,92.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,A trip back in time from the present to...,Timecrimes,7.0,308
4066,1500000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 9648, ""n...",http://www.3l-filmverleih.de/rec,8329,"[{""id"": 321, ""name"": ""terror""}, {""id"": 1523, ""...",es,[REC],A television reporter and cameraman follow eme...,31.691617,"[{""name"": ""Filmax"", ""id"": 3631}]","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2007-04-10,30448000,78.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,One witness. One camera,[REC],7.1,934
4089,2000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",NaN,55,"[{""id"": 960, ""name"": ""homeless person""}, {""id""...",es,Amores perros,Three different people in Mexico City are cata...,23.281616,"[{""name"": ""Altavista Films"", ""id"": 5084}, {""na...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2000-06-16,20908467,154.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Love. Betrayal. Death.,Amores perros,7.6,521
4174,1800000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://padreamaro.ad2.com/site/home_eng.htm,542,"[{""id"": 1786, ""name"": ""heart attack""}, {""id"": ...",es,El Crimen del Padre Amaro,The young Father Amaro is put to the test. He ...,2.179428,"[{""name"": ""Instituto Mexicano de Cinematograf\...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2002-10-01,0,118.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Lead us not into temptation,The Crime of Padre Amaro,6.2,36
4192,0,"[{""id"": 18, ""name"": ""Drama""}]",http://www.foxsearchlight.com/underthesamemoon,32579,"[{""id"": 10183, ""name"": ""independent film""}, {""...",es,La misma luna,Tells the parallel stories of nine-year-old Ca...,2.756435,"[{""name"": ""The Weinstein Company"", ""id"": 308},...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",2008-03-20,23311391,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The love between a mother and a son knows no B...,Under the Same Moon,7.0,28
4226,1500000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,18079,"[{""id"": 612, ""name"": ""hotel""}, {""id"": 3202, ""n...",es,Nueve Reinas,An Argentinian crime drama revolving around a ...,8.589355,"[{""name"": ""Naya Films S.A."", ""id"": 4718}, {""na...","[{""iso_3166_1"": ""AR"", ""name"": ""Argentina""}]",2000-08-31,0,114.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Sticky & Square,Nine Queens,7.4,153
4260,1400000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",NaN,44413,"[{""id"": 612, ""name"": ""hotel""}, {""id"": 10809, ""...",es,La niña santa,Amalia is an adolescent girl who is caught in ...,0.684881,"[{""name"": ""R&C Produzioni"", ""id"": 19385}, {""na...","[{""iso_3166_1"": ""AR"", ""name"": ""Argentina""}, {""...",2004-05-06,0,106.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,She is both temptation and salvation.,The Holy Girl,6.8,10
4294,1300000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,215924,"[{""id"": 187056, ""name"": ""woman director""}]",es,Los insólitos peces gato,Young Claudia works in a supermarket where she...,1.473405,"[{""name"": ""Cine Canibal"", ""id"": 16496}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",2013-08-10,0,87.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,The Amazing Catfish,5.7,17
4404,1000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,186935,"[{""id"": 10175, ""name"": ""drug cartel""}, {""id"": ...",es,Heli,Heli must try and protect his young family whe...,3.629777,"[{""name"": ""Mantarraya Producciones"", ""id"": 863...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2013-08-09,0,105.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"Police corruption, drug trafficking, sexual ex...",Heli,6.2,32
4416,0,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 18, ...",NaN,258755,[],es,A escondidas,At the age of 14 the world around you changes ...,1.233688,"[{""name"": ""Baleuko S.L."", ""id"": 10026}, {""name...","[{""iso_3166_1"": ""ES"", ""name"": ""Spain""}]",2014-10-03,0,96.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,NaN,Hidden Away,7.6,26
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238

In [30]:
tmdb ["original_language"].unique()

<StringArray>
['en', 'ja', 'fr', 'zh', 'es', 'de', 'hi', 'ru', 'ko', 'te', 'cn', 'it', 'nl',
 'ta', 'sv', 'th', 'da', 'xx', 'hu', 'cs', 'pt', 'is', 'tr', 'nb', 'af', 'pl',
 'he', 'ar', 'vi', 'ky', 'id', 'ro', 'fa', 'no', 'sl', 'ps', 'el']
Length: 37, dtype: str

In [31]:
print(tmdb ["release_date"].min(), tmdb ["release_date"].max())

1916-09-04 2017-02-03